### ISSUE TITLE
Migrate to TypeScript Using Rspack

### ISSUE THREAD

**Issue by chrisllontop** [chrisllontop/qrex#1]
Upgrade the project codebase from JavaScript to TypeScript to enhance code quality, maintainability, and developer experience. Utilize Rspack as the module bundler to improve build performance and optimization. Ensure that the project supports both CommonJS and ECMAScript Modules (ESM) for wider compatibility across different environments.

### Tasks

- **TypeScript Migration**
  - Convert all existing JavaScript files to TypeScript (`.ts`) files.
  - Set up a `tsconfig.json` file with appropriate compiler options.

- **Rspack Integration**
  - Replace the current bundler with Rspack and configure it for the project.
  - Configure Rspack to output builds compatible with both CommonJS and ESM modules.
  - Update build scripts and dependencies to accommodate Rspack and dual module outputs.

- **Module Compatibility**
  - Ensure `package.json` has correct fields (`"main"` for CommonJS and `"module"` for ESM) pointing to the respective build outputs.
  - Pay attention to differences in module resolution and syntax between CommonJS and ESM.
  - Consider using conditional exports in `package.json` if necessary.

- **Code Quality and Testing**
  - Resolve any type errors and ensure all TypeScript code compiles successfully.
  - Test the entire application to verify that all functionalities remain intact after the migration.

**Comment by mHuzefa** [comment]
Hi @chrisllontop, how to contribute into this issue? I'm willing to work on this issue.

**Comment by chrisllontop** [comment]
@mHuzefa Sure, please feel free to open a PR when it's ready.
